# Generated by Django 4.2.7 on 2025-11-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cartera", "0002_abono_descripcion_deuda_descripcion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEUDA_VENCIDA_CLIENTE", "Deuda Vencida - Cliente"),
                            ("DEUDA_VENCIDA_ADMIN", "Deuda Vencida - Administrador"),
                            ("RECORDATORIO_PAGO", "Recordatorio de Pago"),
                        ],
                        max_length=30,
                    ),
                ),
                ("destinatario_email", models.EmailField(max_length=254)),
                ("asunto", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADA", "Enviada"),
                            ("FALLIDA", "Fallida"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("error_mensaje", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cartera.cliente",
                    ),
                ),
                (
                    "deuda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cartera.deuda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
