# Generated by Django 4.2.7 on 2025-10-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Deuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("pagada", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cartera.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "deuda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cartera.deuda"
                    ),
                ),
            ],
        ),
    ]
