# Generated by Django 4.2.7 on 2025-10-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abono",
            name="descripcion",
            field=models.CharField(blank=True, default="Abono a deuda", max_length=200),
        ),
        migrations.AddField(
            model_name="deuda",
            name="descripcion",
            field=models.CharField(
                blank=True, default="Deuda pendiente", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="deuda",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
