# Generated by Django 4.2.7 on 2025-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_abono_descripcion_deuda_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
