# Generated by Django 4.2.7 on 2025-09-27 20:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VF", "Venta Facturada"),
                            ("VNF", "Venta No Facturada"),
                            ("IO", "Otro Ingreso"),
                        ],
                        default="VF",
                        max_length=3,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                (
                    "numero_factura",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="CierreCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(unique=True)),
                (
                    "total_ventas_facturadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_ventas_no_facturadas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_otros_ingresos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_calculado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fisico",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("cerrado", models.BooleanField(default=False)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "usuario_cierre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de Caja",
                "verbose_name_plural": "Cierres de Caja",
                "ordering": ["-fecha"],
            },
        ),
    ]
