# Generated by Django 4.2.7 on 2025-11-24 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaccion",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
